#!/bin/bash
clear
echo "--------------------------"
echo "compil-exec pour projet world of poo"

javac -cp ./lib/*:. MyGame.java 2> erreur

if [[ -z $(cat erreur) ]] ; then
	rm erreur
	echo "Exécution du programme :"
	echo "--------------------------"
	java -cp ./lib/*:. MyGame
else
	echo "Erreur de compilation"
	echo "--------------------------"
	echo ""
	cat erreur
	echo ""
	echo "--------------------------"
	echo "Message disponible dans le fichier \"erreur\""
fi
echo ""

##Auteur : Lucas C.
## Me tenir au courant s'il y a des évolutions/améliorations cousi@et.esiea.fr , ou pour tout feedback. merci d'avance, feignasse ! ;-)
